---

- name: Include task variables
  include_vars: "{{ item }}"
  with_items:
    - apt.yml

- name: Update any existing packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ apt_pkgs | default({}) }}"
  become: yes

- name: Set openjdk 11 as default
  alternatives:
    name="{{ java.exe }}"
    link="/usr/bin/{{ java.exe }}"
    path="{{ java.path }}/{{ java.exe }}"
  with_items:
    - { path: "{{ sw_jdk_java_home }}/bin", exe: 'java' }
    - { path: "{{ sw_jdk_java_home }}/bin", exe: 'keytool' }
    - { path: "{{ sw_jdk_java_home }}/bin", exe: 'javac' }
    - { path: "{{ sw_jdk_java_home }}/bin", exe: 'javadoc' }
  loop_control:
    loop_var: java
  become: yes

